Fix/readme makefile
nitrictech/nitric pull request #158
Opened 2021-09-06 05:57 UTC by medgar-nitric

2021-09-06 05:58 UTC, tjholm approved these changes

2021-09-08 03:26 UTC, tjholm requested changes

2021-09-08 03:26 UTC, tjholm commented on makefile
> +	@cat ./tools/tools.go | grep _ | awk -F'"' '{print $$2}' | xargs -tI % go get -d %
Looks like this change is impacting software installs for CI.

2021-09-09 09:06 UTC, jyecusch approved these changes

2021-09-14 05:13 UTC, tjholm commented
All approved, just need a quick rebase to resolve conflicts.

2021-09-14 05:13 UTC, tjholm approved these changes

2021-09-15 23:10 UTC, merged