Update import path to github.com/nitrictech/nitric
nitrictech/nitric pull request #193
Opened 2021-12-05 23:48 UTC by asalkeld

2021-12-05 23:53 UTC, tjholm approved these changes
LGTM

2021-12-05 23:59 UTC, tjholm requested changes
Need to do a find and replace on files for integration tests (located under `tests/`).

2021-12-06 00:01 UTC, tjholm approved these changes

2021-12-06 00:26 UTC, davemooreuws approved these changes

2021-12-06 00:36 UTC, merged