GCP: Direct schedule handling
nitrictech/nitric pull request #299
Opened 2022-07-14 17:52 UTC by tjholm

2022-07-24 22:52 UTC, asalkeld approved these changes

2022-08-22 01:01 UTC, HomelessDinosaur requested changes

2022-08-22 01:01 UTC, HomelessDinosaur commented on pkg/plugins/gateway/base_http/http.go
> +	DefaultTopicRoute    = "/x-nitric-topic/:name"
Change :name -> {name}

2022-08-22 01:01 UTC, HomelessDinosaur commented on pkg/plugins/gateway/cloudrun/http.go
> +	r.ANY("/x-nitric-schedule/{name}", handleSchedule(p))
Use DefaultScheduleRoute and DefaultTopicRoute

2022-09-12 03:10 UTC, tjholm commented
Closing until we have a better versioning/release strategy between the CLI and membrane.

2022-09-12 03:10 UTC, closed without merging