Azure: Update subscription handlers
nitrictech/nitric pull request #300
Opened 2022-07-14 20:48 UTC by tjholm

Also add placeholder schedule handler endpoint

2022-07-24 23:38 UTC, HomelessDinosaur approved these changes

2022-08-22 01:00 UTC, HomelessDinosaur requested changes

2022-08-22 01:00 UTC, HomelessDinosaur commented on pkg/plugins/gateway/appservice/http.go
> +	r.ANY("/x-nitric-schedule/{name}", handleSchedule(p))
Use DefaultScheduleRoute and DefaultTopicRoute

2022-08-22 01:00 UTC, HomelessDinosaur commented on pkg/plugins/gateway/base_http/http.go
> +	DefaultTopicRoute    = "/x-nitric-topic/:name"
Change :name -> {name}

2022-09-11 23:30 UTC, HomelessDinosaur approved these changes

2022-09-12 03:09 UTC, tjholm commented
Closing until we have a better versioning/release strategy between the CLI and membrane.

2022-09-12 03:09 UTC, closed without merging