Refactor Workers
nitrictech/nitric pull request #302
Opened 2022-07-25 00:25 UTC by tjholm

Refactor workers to better separate interfaces. This will allow for easier testing as well as better separation of protocol handling vs. worker types e.g. A subscription worker could have a gRPC handler or a HTTP handler.

2022-07-29 02:59 UTC, jyecusch approved these changes
I like the separation, but I think we could improve the naming for these things. handlers/worker feel overloaded and hard to know which is which without digging into the code.

The handler is more like a receiver/adapter for streams/events/etc. and the worker actually handles/does the work triggered/requested by the events.

2022-08-01 06:19 UTC, tjholm commented
> I like the separation, but I think we could improve the naming for these things. handlers/worker feel overloaded and hard to know which is which without digging into the code.
> 
> The handler is more like a receiver/adapter for streams/events/etc. and the worker actually handles/does the work triggered/requested by the events.

Will refactor this to rename to adapter

2022-08-04 02:50 UTC, HomelessDinosaur requested changes

2022-08-04 02:50 UTC, HomelessDinosaur commented
Just those small changes, otherwise looks good

2022-08-16 04:58 UTC, tjholm commented on pkg/worker/route_worker.go
> +func NewRouteWorker(handler Adapter, opts *RouteWorkerOptions) *RouteWorker {
done

2022-08-16 04:58 UTC, tjholm commented on pkg/worker/faas_worker.go
> +func NewFaasWorker(handler Adapter) *FaasWorker {
done

2022-08-18 00:42 UTC, HomelessDinosaur approved these changes

2022-08-18 00:43 UTC, merged