Add delayed messaging
nitrictech/nitric pull request #331
Opened 2022-10-05 03:14 UTC by tjholm

Implemented for GCP and AWS. 

Azure to be implemented with schedules.

Local implementation to be done with dev release (event management plugin is managed in the CLI).

2022-10-05 06:21 UTC, tjholm commented on contracts/proto/event/v1/event.proto
> +  // An optional delay specified in seconds (minimum 30 seconds)
There is a latency cost to the delayed messaging, and we may not be able to guarantee accuracy at very low values. It seems arbitrary, but want to ensure that users aren't incurring additional costs and getting a degraded experience at the same time.

2022-10-11 05:22 UTC, asalkeld reviewed
some minor nits

2022-10-11 05:22 UTC, asalkeld commented on pkg/plugins/events/sns/sns.go
> +		return fmt.Errorf("unable to publish message: %v", err)
```suggestion
		return fmt.Errorf("unable to publish message: %w", err)
```

2022-10-11 05:22 UTC, asalkeld commented on pkg/plugins/events/sns/sns.go
> +		return fmt.Errorf("error finding state machine: %v", err)
```suggestion
		return fmt.Errorf("error finding state machine: %w", err)
```

2022-10-11 05:22 UTC, asalkeld commented on pkg/plugins/events/sns/sns.go
> +		return fmt.Errorf("error finding state machine:: %v", err)
```suggestion
		return fmt.Errorf("error finding state machine:: for topic %s", topic)
```

2022-10-11 05:22 UTC, asalkeld commented on pkg/plugins/events/sns/sns.go
> +		return fmt.Errorf("error starting state machine execution: %v", err)
```suggestion
		return fmt.Errorf("error starting state machine execution: %w", err)
```

2022-10-12 05:57 UTC, asalkeld approved these changes

2022-10-12 23:46 UTC, HomelessDinosaur requested changes

2022-10-12 23:46 UTC, HomelessDinosaur commented on contracts/proto/event/v1/event.proto
> +  uint32 delay = 3 [(validate.rules).uint32 = {ignore_empty: true, gte:30, lte: 2592000}];
```suggestion
  uint32 delay = 3 [(validate.rules).uint32 = {ignore_empty: true, gte:10, lte: 2592000}];
```

2022-10-13 00:00 UTC, tjholm commented on contracts/proto/event/v1/event.proto
> +  uint32 delay = 3 [(validate.rules).uint32 = {ignore_empty: true, gte:30, lte: 2592000}];
Done

2022-10-13 00:08 UTC, HomelessDinosaur approved these changes

2022-10-13 03:49 UTC, merged