GCP resources API
nitrictech/nitric pull request #336
Opened 2022-10-18 03:32 UTC by tjholm

Add Details API for GCP resources.

2022-10-18 04:42 UTC, HomelessDinosaur requested changes

2022-10-18 04:42 UTC, HomelessDinosaur commented on pkg/providers/gcp/core/provider.go
> +func (g *gcpProviderImpl) Details(typ common.ResourceType, name string) (*common.DetailsResponse[any], error) {
```suggestion
func (g *gcpProviderImpl) Details(type common.ResourceType, name string) (*common.DetailsResponse[any], error) {
```

2022-10-18 04:42 UTC, HomelessDinosaur commented on pkg/providers/gcp/core/provider.go
> +	// there should only be a single entry in this array, we'll grab the first and then brake
```suggestion
	// there should only be a single entry in this array, we'll grab the first and then break
```

2022-10-19 02:58 UTC, tjholm commented on pkg/providers/gcp/core/provider.go
> +func (g *gcpProviderImpl) Details(typ common.ResourceType, name string) (*common.DetailsResponse[any], error) {
`type` is a reserved keyword in golang

2022-10-19 03:32 UTC, davemooreuws approved these changes
LGTM

2022-10-19 23:18 UTC, HomelessDinosaur approved these changes

2022-10-19 23:33 UTC, merged