Add Azure ApiManagement service retrieval
nitrictech/nitric pull request #337
Opened 2022-10-19 02:56 UTC by tjholm

2022-10-20 00:29 UTC, HomelessDinosaur requested changes
Minor typo

2022-10-20 02:44 UTC, tjholm commented on pkg/providers/azure/core/provider.go
> +func (p *azProviderImpl) Details(typ common.ResourceType, name string) (*common.DetailsResponse[any], error) {
`type` is a reserved keywork in go
![image](https://user-images.githubusercontent.com/13415171/196843914-e368a6d6-4ba2-4e65-a0ed-b002669f8d15.png)

2022-10-20 02:47 UTC, HomelessDinosaur approved these changes

2022-10-25 23:42 UTC, asalkeld approved these changes

2022-10-27 21:38 UTC, merged