Add dockerfiles for deploy servers
nitrictech/nitric pull request #370
Opened 2023-02-01 00:18 UTC by asalkeld

2023-02-01 00:54 UTC, HomelessDinosaur requested changes

2023-02-01 00:54 UTC, HomelessDinosaur commented on cloud/azure/deploy/Dockerfile
> +ADD runtime-azure /usr/bin/
```suggestion
ADD deploy-azure /usr/bin/
```

2023-02-01 00:54 UTC, HomelessDinosaur commented on cloud/azure/deploy/Dockerfile
> +ENTRYPOINT ["runtime-azure"]
```suggestion
ENTRYPOINT ["deploy-azure"]
```

2023-02-01 00:54 UTC, HomelessDinosaur commented on Makefile
> +	$(MAKE) dockerimage -C cloud/azure
```suggestion
	$(MAKE) dockerimage -C cloud/azure
	$(MAKE) dockerimage -C cloud/gcp
```

2023-02-01 03:54 UTC, tjholm commented on cloud/Dockerfile
> +  docker-ce && \
Thinking of slimming things down a bit. Do we actually need full docker-ce? Or could we get away with just docker-cli with the socket forwarding we'll need to do anyway?

2023-02-01 03:57 UTC, tjholm commented on cloud/Dockerfile
> +FROM python:3.9-slim AS base
Do we need python?

here is pulumi's base dockerfile sans SDKs:
https://github.com/pulumi/pulumi-docker-containers/blob/main/docker/base/Dockerfile

I don't think we need the SDKs when we're using the automation API. Excluding unnecessary runtimes should save some space

2023-02-01 03:59 UTC, tjholm commented on cloud/Dockerfile
> +  unzip && \
If we use pulumi/pulumi-base we should have everything we need that they rely on.

2023-02-06 07:51 UTC, tjholm commented
Going with binary distribution approach for now.

2023-02-06 07:51 UTC, closed without merging