fix: AWS SNS failure
nitrictech/nitric pull request #441
Opened 2023-05-14 23:04 UTC by tjholm

Ensure that messages flagged as unsuccessful are properly rejected.

2023-05-14 23:06 UTC, davemooreuws approved these changes

2023-05-14 23:06 UTC, HomelessDinosaur approved these changes

2023-05-15 00:36 UTC, davemooreuws requested changes
Looks good, just some tests need fixing

2023-05-29 09:44 UTC, jyecusch approved these changes

2023-05-29 09:44 UTC, merged