feat: add http worker for proxying http frameworks
nitrictech/nitric pull request #467
Opened 2023-06-21 01:11 UTC by HomelessDinosaur

2023-06-26 03:52 UTC, tjholm commented on contracts/proto/faas/v1/faas.proto
> +  int32 port = 2;
Do we want to set this to field 1 before release?

2023-06-26 05:02 UTC, tjholm approved these changes

2023-06-28 00:06 UTC, davemooreuws approved these changes

2023-06-28 00:07 UTC, tjholm requested changes

2023-06-28 00:07 UTC, tjholm commented on contracts/proto/deploy/v1/deploy.proto
> +    int32 port = 2;
is this used at deploy time?

2023-06-28 00:17 UTC, HomelessDinosaur commented on contracts/proto/deploy/v1/deploy.proto
> +    int32 port = 2;
No, will remove.

2023-06-28 01:15 UTC, tjholm approved these changes

2023-06-28 01:16 UTC, merged