ci: Implement gosec in github actions.
nitrictech/nitric pull request #521
Opened 2023-10-18 02:13 UTC by tjholm

2023-10-19 01:20 UTC, jyecusch approved these changes

2023-10-19 03:01 UTC, davemooreuws approved these changes

2023-10-19 03:01 UTC, davemooreuws requested changes
Looks like test suite isn't running in /nitric/cloud/common

2023-10-23 01:43 UTC, davemooreuws approved these changes

2023-10-23 01:44 UTC, merged