feat(gcp): Add same project secret imports for GCP.
nitrictech/nitric pull request #602
Opened 2024-04-09 22:38 UTC by tjholm

2024-04-09 22:58 UTC, jyecusch requested changes

2024-04-09 22:58 UTC, jyecusch commented on cloud/gcp/deploy/config.go
> +	// A map of nitric names to ARNs
```suggestion
	// A map of nitric names to GCP Secret Manager names
```

2024-04-09 22:58 UTC, jyecusch commented on cloud/gcp/deploy/secret.go
> +// tagSecret - tags an existing secret in AWS and adds it to the stack.
```suggestion
// tagSecret - tags an existing secret in GCP and adds it to the stack.
```

2024-04-09 22:58 UTC, jyecusch commented on cloud/gcp/deploy/secret.go
> +// createSecret - creates a new secret in AWS, using the provided name and tags.
```suggestion
// createSecret - creates a new secret in GCP Secret Manager, using the provided name and tags.
```

2024-04-10 07:09 UTC, jyecusch approved these changes

2024-04-10 07:56 UTC, davemooreuws approved these changes

2024-04-10 07:57 UTC, merged