feat: gcp sql database support
nitrictech/nitric pull request #623
Opened 2024-06-11 06:17 UTC by HomelessDinosaur

2024-06-14 02:38 UTC, tjholm requested changes
Changes that fix a gateway to service timeout mismatch have been reverted in the PR.

2024-06-14 02:38 UTC, tjholm commented on cloud/gcp/deploy/api.go
>  			v2doc.Paths[k] = p
This clobbers a fix for gateway route timeouts not matching service timeouts

2024-06-14 02:38 UTC, tjholm commented on cloud/gcp/deploy/api.go
> +func gcpOperation(apiName string, op *openapi2.Operation, urls map[string]string) *openapi2.Operation {
fix reversion of gateway route timeout fix.

2024-06-14 02:38 UTC, tjholm commented on cloud/gcp/deploy/api.go
> -		"deadline":         timeouts[name],
Fix reversion of gateway -> service timeout fixes.

2024-06-14 03:10 UTC, tjholm approved these changes

2024-06-17 23:31 UTC, davemooreuws requested changes
First deploy works well.

But next ones don't apply the migrations at the correct time, the cloud run builds are triggered before the new image is available. I used prisma to test.

Also might need to include similar dependencies for deploying services after migrations, like these: https://github.com/nitrictech/nitric/pull/627

2024-08-27 23:24 UTC, jyecusch approved these changes

2024-08-28 07:35 UTC, davemooreuws commented on cloud/gcp/deploy/sql.go
> +		DeletionPolicy: pulumi.String(a.GcpConfig.Databases[name].DeletionPolicy),
I seem to be getting a nil pointer error here.

```
iagnostics:
  pulumi:pulumi:Stack (nitric-prisma-final-nitric-prisma-final-gcpsql):
    error: an unhandled error occurred: 1 error occurred:
        * recovered panic: runtime error: invalid memory address or nil pointer dereference
     Stack: goroutine 90 [running]:
    runtime/debug.Stack()
        C:/Program Files/Go/src/runtime/debug/stack.go:24 +0x5e
    github.com/nitrictech/nitric/cloud/common/deploy/provider.(*PulumiProviderServer).Up.createPulumiProgramForNitricProvider.func2.1()
        C:/projects/nitric/nitric/cloud/common/deploy/provider/pulumi.go:80 +0x3d
    panic({0x2fb66a0?, 0x86e6000?})
        C:/Program Files/Go/src/runtime/panic.go:770 +0x132
    github.com/nitrictech/nitric/cloud/gcp/deploy.(*NitricGcpPulumiProvider).SqlDatabase(0xc00034a9c0, 0xc0007c5440, {0x43f1380, 0xc0007fcdd0},
{0xc0001aa070, 0x5}, 0xc0005deac0)
        C:/projects/nitric/nitric/cloud/gcp/deploy/sql.go:48 +0x1ff
```

2024-08-28 07:53 UTC, davemooreuws requested changes
Issue with deletion policy found, see comments.

2024-08-28 22:40 UTC, davemooreuws commented on cloud/gcp/deploy/sql.go
> +		DeletionPolicy: pulumi.String(a.GcpConfig.Databases[name].DeletionPolicy),
Suggestion, check for a.GcpConfig.Databases[name] != nil then apply the deletion policy.

2024-08-29 02:49 UTC, davemooreuws commented on cloud/gcp/runtime/sql/cloud_sql.go
This needs to be added to the server.go

2024-08-29 06:23 UTC, davemooreuws commented
Last issue is making sure services are created after the cloud build run ends.

2024-09-13 01:43 UTC, tjholm commented
Fixes for existing issues implemented up/down is smooth now. Should be good to release.

2024-09-13 02:34 UTC, merged