fix: Deploy services after database migrations.
nitrictech/nitric pull request #627
Opened 2024-06-17 03:01 UTC by tjholm

2024-06-17 03:03 UTC, HomelessDinosaur commented on cloud/aws/deploy/sql.go
> +	err := ctx.RegisterComponentResource("nitric:cloud:aws:SqlDatabase", name, a.SqlDatabases[name], pulumi.Parent(parent))
```suggestion
	err := ctx.RegisterComponentResource("nitricaws:SqlDatabase", name, a.SqlDatabases[name], pulumi.Parent(parent))
```

2024-06-17 06:18 UTC, davemooreuws requested changes
Looks good, just a typo I think

2024-06-17 06:18 UTC, davemooreuws commented on cloud/aws/deploy/service.go
> +		sqlDatasesMigrated := lo.Map(lo.Values(a.SqlDatabases), func(item *RdsDatabase, idx int) interface{} {
```suggestion
		sqlDatabasesMigrated := lo.Map(lo.Values(a.SqlDatabases), func(item *RdsDatabase, idx int) interface{} {
```

2024-06-17 06:18 UTC, davemooreuws commented on cloud/aws/deploy/service.go
> +		databasesMigrated := pulumi.All(sqlDatasesMigrated...).ApplyT(func(migrated []interface{}) bool {
```suggestion
		databasesMigrated := pulumi.All(sqlDatabasesMigrated...).ApplyT(func(migrated []interface{}) bool {
```

2024-06-17 23:29 UTC, davemooreuws approved these changes

2024-06-26 02:29 UTC, HomelessDinosaur approved these changes

2024-06-26 20:00 UTC, merged