feat: Azure sql database support
nitrictech/nitric pull request #631
Opened 2024-06-19 12:36 UTC by HomelessDinosaur

2024-06-21 01:57 UTC, tjholm requested changes

2024-06-21 01:57 UTC, tjholm commented on cloud/azure/deploy/sql.go
> +		})
Add parent config for this

2024-06-21 01:57 UTC, tjholm commented on cloud/azure/deploy/sql.go
> +		})
parent config

2024-06-27 05:05 UTC, tjholm approved these changes
encountered minor issues with redeployments, but mostly seemed to be network error related. All good for preview I think.

2024-07-01 00:46 UTC, jyecusch approved these changes

2024-07-01 01:46 UTC, merged