docs: update readme
nitrictech/nitric pull request #642
Opened 2024-07-17 02:55 UTC by jyecusch

Update the main project readme to remove the outdated diagram and include useful links to various documentation pages.

2024-07-17 03:07 UTC, davemooreuws requested changes

2024-07-17 03:10 UTC, davemooreuws requested changes

2024-07-17 03:10 UTC, davemooreuws commented on README.md
> +This is the only code needed to deploy a working application to any cloud provider you choose, using [`nitric up`](https://nitric.io/docs/getting-started/deployment). Nitric can deploy this applicati
```suggestion
This is the only code needed to deploy a working application to any cloud provider using [`nitric up`](https://nitric.io/docs/getting-started/deployment). Nitric can deploy this application using automatically generated [Pulumi](https://nitric.io/docs/reference/providers/pulumi), [Terraform](https://nitric.io/docs/reference/providers/terraform) or [any other automation tools](https://nitric.io/docs/reference/providers/custom/building-custom-provider) of your choice.
```

2024-07-18 02:16 UTC, davemooreuws approved these changes

2024-07-18 04:21 UTC, tjholm approved these changes

2024-07-18 04:21 UTC, merged