chore: add windows install scripts
nitrictech/nitric pull request #645
Opened 2024-07-18 06:29 UTC by davemooreuws

2024-07-18 06:41 UTC, HomelessDinosaur requested changes

2024-07-18 06:41 UTC, HomelessDinosaur commented on cloud/aws/Makefile
> +		cp bin/deploy-awstf "$${HOME}/.nitric/providers/nitric/awstf-0.0.1.exe"; \
```suggestion
		cp bin/deploy-awstf "${HOME}/.nitric/providers/nitric/awstf-0.0.1.exe"; \
```

2024-07-18 06:41 UTC, HomelessDinosaur commented on cloud/aws/Makefile
> +		rm -f "${HOME}/.nitric/providers/nitric/aws-0.0.1.exe"; \
```suggestion
        @rm -f "${HOME}/.nitric/providers/nitric/aws-0.0.1"*;
        @rm -f "${HOME}/.nitric/providers/nitric/awstf-0.0.1"*;
	@if [ "$(OS)" == "Windows_NT" ]; then \
```

2024-07-19 03:38 UTC, jyecusch approved these changes

2024-07-19 07:09 UTC, merged